### ISSUE TITLE
ConnectivityChangeCount doesn't mean convergence

### ISSUE THREAD

**Issue by XLuyu** [kwartile/connected-component#1]
Hi,

I'm interested in this project. After I read the code, I think ConnectivityChangeCount only count the change in number of edges, not change of edges. This may lead to mistake.
Here is a counterexample:

```scala
val g = sc.parallelize(Array(List(1L,4L), List(2L,4L),List(2L,5L), 
                             List(3L,5L),List(1L,6L),List(3L,6L)))
```
Which build a graph:
```
  6
/    \
1  2  3
\ /\ /
 4  5
```

Then I run
```scala
val (a,b,c) = ConnectedComponent.run(sc,g,1000)
a.collect
```
Spark gave this:
```scala
Array[(Long, Long)] = Array((1,1), (2,2), (3,3), (4,1), (2,1), (5,2), (3,2), (6,1), (3,1))
```

Please check this case. Thank you!

**Comment by kumarshirish** [comment]
Thanks for pointing this out.  I have found the fix will check it on after testing it out.

**Comment by kumarshirish** [comment]
Checked in the fix.  Would love to hear your feedback.
