### ISSUE TITLE
Documentation request for the proper spark related settings

### ISSUE THREAD

**Issue by javadba** [kwartile/connected-component#2]
On the README.md the following is stated:

> We indeed had to to try various Spark related configurations, including executor memory size, driver memory size, yarn memory overhead, network timeout, and number of partitions to successfully run the implementation.

Would you be  able to post some of those settings - and if you have the time also some note about why/under what conditions they were chosen?  thanks!

**Comment by kumarshirish** [comment]
Unfortunately, the settings were proprietary to the implementation we did and due to contractual restrictions, we cannot post those settings.  But primarily the settings were executor size, driver size, network timeout, yarn overhead, and partition size.
