### ISSUE TITLE
function largerStar might go wrong 

### ISSUE THREAD

**Issue by kxzhai** [kwartile/connected-component#4]
In paper "connected component in mapreduce and beyond", while doing largerStar, it usually connect all strictly larger neighbors to the min neighbor including self.  
But in the implementation, as shown in code snippet below: 
((neighbor > self && neighbor != minNode) || (neighbor == self))
it will emit edge from self to minNode.

Test below easily demonstrate this:
before largeStar:
scala> nodePairs.collect.foreach(print _)
(1,8)(9,8)(8,5)(7,3)(3,2)(6,3)(6,4)(8,7)
after that:
scala> largeStar(nodePairs)._1.collect.foreach(print _)
(1,1)(8,1)(2,2)(3,2)(3,2)(6,2)(7,2)(4,4)(6,4)(5,5)(8,5)(6,3)(7,3)(8,3)(8,1)(9,1)(9,8)
 which is obviously wrong.

**Comment by kumarshirish** [comment]
Thanks for the feedback.  I will post a fix in a couple of days.

**Comment by kumarshirish** [comment]
Your reported problem is fixed.  Thanks for the feedback!
