### ISSUE TITLE
Why is the input a list of cliques?

### ISSUE THREAD

**Issue by jnmiller** [kwartile/connected-component#5]
Thank you for open sourcing this code. First, I'd like to note that I was not able to send email to the address given in the README (labs@kwartile.com): the error was mail delivery failure.

My main issue is that the README states that the input to your algorithm is a list of cliques. However, finding all cliques in a graph is a very hard problem (NP-complete I believe) but a basic connected components algorithm is doable in at least linear time, so why does your code require finding all cliques first? Are you using a different definition of "clique"? The paper cited in the README does not mention cliques at all.

**Comment by kumarshirish** [comment]
We will check the email address.

We are not finding cliques in a graph.  And you are correct, we are not using the term clique as defined in the graph theory.  By a clique, we mean that vertices in the clique are connected.
