### ISSUE TITLE
Performance and input - questions

### ISSUE THREAD

**Issue by kobi-lemberg** [kwartile/connected-component#6]
Hi Kumar,

First I would like to say thanks for having this code, it is really good comparing to GraphX performance, also the API is much easier to understand.

Our use case is to find a connected component in large graph. we are creating the graph based on other input and we can manipulate the way we are creating the edges (i.e creating them as a star (partially) or like a "linked list" and we are trying to find the best way to optimize the input in order to speed the connected component part.

We did some performance testing (with 30 spark executor where each executor has 12 cores) and we found that:
for Graph1:
vertex count: 1458232
edge count: 794924
connected components: 795098
It took 5 minutes to find connected components

In Graph2:
vertex count: 46165451
edge count: 37572770
connected components: 17908024
it took 8 hours to find connected components.

Several questions:
1. what is the best "input" (graph shape/edges shape) that makes the code to run faster per connected component?  star? linked-list? 
is it correct that having the maximum needed edges as an input will perform better than having the minimum needed edges to achieve the same connected components? we tried to save edges but we saw it gave us bad result comparing to other run with more edges.
Examples:
Graph (each line is clique): 
a,b,c
a,b
d,e,f

edges in scenario 1 (better results): (a,b)(a,c)(b,c)(d,e)(d,f)(e,f)
edges in scenario 2 : (a,b)(a,c)(d,e)(d,f)
Are there any differences in terms of performance? we can manipulate our input to achieve the same connected component with different edges, this is why we are asking.

2. if I compare graph1 to graph2, how come Graph2 runs 80 times slower than Graph1? I did the following computation, let me know if I'm wrong:

Graph2 edges/Graph1 edges = ~47
Graph2 vertices/Graph1 vertices = ~31

31 + 47 = 78 which is close to 80, could this be the explanation how come it runs 80 times slower? 

I couldn't find other way to contact with you to ask questions....
if you can send me an email to kobi.lemberg@gmail.com we can discuss more.. please feel free to close this issue.

thanks!

**Comment by kumarshirish** [comment]
As discussed the performance issue was related to the job configuration.  There were too many small partitions and after reducing the number of partitions the performance issue got resolved.
